-- ==========================================
-- GALA DATABASE SCHEMA
-- ==========================================

-- Drop in reverse order of creation (child tables first)
DROP TABLE IF EXISTS public.user_friends CASCADE;
DROP TABLE IF EXISTS public.event_invitations CASCADE;
DROP TABLE IF EXISTS public.event_members CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ------------------------------------------
-- 1. USERS
-- ------------------------------------------

create table public.users (
  user_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  username text not null,
  user_email text not null,
  first_name text not null,
  last_name text not null,
  updated_at timestamp with time zone not null default now(),
  avatar_url text null,
  auth_id uuid null,
  constraint users_pkey primary key (user_id),
  constraint users_user_email_key unique (user_email),
  constraint users_username_key unique (username)
) TABLESPACE pg_default;

-- ------------------------------------------
-- 2. EVENTS
-- ------------------------------------------

create table public.events (
  event_id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  organizer_id bigint not null,
  event_title text not null,
  event_description text null,
  location_lat numeric null,
  location_long numeric null,
  start_timestamp timestamp with time zone not null,
  end_timestamp timestamp with time zone not null,
  event_status text not null,
  location_name text null,
  constraint events_pkey primary key (event_id),
  constraint events_organizer_id_fkey foreign KEY (organizer_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;

-- ------------------------------------------
-- 3. EVENT_MEMBERS
-- ------------------------------------------

create table public.event_members (
  event_id bigint not null,
  user_id bigint not null,
  joined_at timestamp with time zone not null default now(),
  rsvp_status text not null default ''::text,
  constraint event_members_pkey primary key (event_id, user_id),
  constraint fk_event foreign KEY (event_id) references events (event_id) on delete CASCADE,
  constraint fk_user foreign KEY (user_id) references users (user_id) on delete CASCADE,
  constraint check_rsvp_status check (
    (
      rsvp_status = any (
        array[
          'attending'::text,
          'maybe'::text,
          'declined'::text,
          'pending'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

-- ------------------------------------------
-- 4. EVENT_INVITATIONS
-- ------------------------------------------

create table public.event_invitations (
  invitation_id bigint generated by default as identity not null,
  event_id bigint not null,
  sender_id bigint not null,
  recipient_id bigint not null,
  invitation_status text not null default 'pending'::text,
  created_at timestamp with time zone not null default now(),
  constraint event_invitations_pkey primary key (invitation_id),
  constraint unique_invite unique (event_id, recipient_id),
  constraint fk_event foreign KEY (event_id) references events (event_id) on delete CASCADE,
  constraint fk_recipient foreign KEY (recipient_id) references users (user_id) on delete CASCADE,
  constraint fk_sender foreign KEY (sender_id) references users (user_id) on delete CASCADE,
  constraint event_invitations_status_check check (
    (
      invitation_status = any (
        array[
          'pending'::text,
          'accepted'::text,
          'declined'::text,
          'ignored'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

-- ------------------------------------------
-- 5. USER_FRIENDS
-- ------------------------------------------

create table public.user_friends (
  user_id_1 bigint not null,
  user_id_2 bigint not null,
  friend_status text not null default 'pending'::text,
  created_at timestamp with time zone not null default now(),
  constraint friendships_pkey primary key (user_id_1, user_id_2),
  constraint friendships_user_id_1_fkey foreign KEY (user_id_1) references users (user_id) on delete CASCADE,
  constraint friendships_user_id_2_fkey foreign KEY (user_id_2) references users (user_id) on delete CASCADE,
  constraint friend_status_check check (
    (
      friend_status = any (
        array[
          'pending'::text,
          'accepted'::text,
          'declined'::text,
          'blocked'::text
        ]
      )
    )
  ),
  constraint no_self_friendship check ((user_id_1 <> user_id_2))
) TABLESPACE pg_default;